import '@styles/globals.css'
import Navbar from '@components/Navbar'
import Footer from '@components/Footer'

export const metadata = {
  title: 'portfolio4u - A Personal portfolio website',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
